region: us-east-2
vpc:
  stackId: DjangoDeployVpcStack
  constructId: DjangoDeployVpc
  name: django-deploy-vpc
  cidr: 10.0.0.0/16
  securityGroup:
    public:
      constructId: PublicSecurityGroup
      name: django-deploy-public-sg
    private:
      constructId: PrivateSecurityGroup
      name: django-deploy-private-sg
    bastion:
      constructId: BastionSecurityGroup
      name: django-deploy-bastion-sg
    isolated:
      constructId: IsolatedSecurityGroup
      name: django-deploy-isolated-sg
rds:
  stackId: DjangoDeployRdsStack
  db:
    constructId: DjangoDeployRds
    dbName: db_django_deploy
    masterUsername: root
    backupRetention: 7
    backupPreferredWindow: "18:00-20:00"
    parameterGroupConstructId: DjangoDeployRdsParameterGroup
  bastion:
    constructId: DjangoDeployBastionHost
    hostName: django-deploy-bastion-ec2
    keyName: django-deploy-bastion-key